const money=new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP",maximumFractionDigits:2});
const $=s=>document.querySelector(s),esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),num=v=>Number(v||0);
const statusEl=$("#salesPageStatus"),contentEl=$("#salesContent"),summaryEl=$("#salesSummary"),tableBody=$("#salesTableBody"),cardsEl=$("#salesCards"),dialog=$("#saleDialog"),form=$("#saleForm"),formStatus=$("#saleFormStatus"),titleEl=$("#saleDialogTitle");
const itemDialog=$("#expenseItemDialog"),itemForm=$("#expenseItemForm"),profileDialog=$("#expenseProfileDialog"),profileForm=$("#expenseProfileForm");
const filters={search:$("#salesSearch"),from:$("#salesDateFrom"),to:$("#salesDateTo"),source:$("#salesSource"),status:$("#salesStatusFilter")};
let records=[],expenseItems=[],expenseUsages=[],expenseProfiles=[],profileItems=[];
const revenue=r=>num(r.gross_amount)+num(r.shipping_amount),usageForSale=id=>expenseUsages.filter(u=>String(u.sales_record_id)===String(id)),usageCostForSale=id=>usageForSale(id).reduce((s,u)=>s+num(u.quantity)*num(u.unit_cost_snapshot),0),expenses=r=>num(r.cost_amount)+num(r.platform_fees)+num(r.other_expenses)+usageCostForSale(r.id),net=r=>revenue(r)-expenses(r);
const usedForItem=id=>expenseUsages.filter(u=>String(u.expense_item_id)===String(id)).reduce((s,u)=>s+num(u.quantity),0);
const localInputDate=(value=new Date())=>{const d=new Date(value),p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`};

async function verifyAccess(){const{data:{user}}=await supabaseClient.auth.getUser();if(!user)return location.replace("admin.html");const{data,error}=await supabaseClient.rpc("is_admin");if(error||data!==true)return location.replace("admin.html");await loadAll()}
async function loadAll(){statusEl.textContent="Loading sales…";const results=await Promise.all([supabaseClient.from("sales_records").select("*").order("sale_date",{ascending:false}),supabaseClient.from("expense_items").select("*").order("name"),supabaseClient.from("sales_expense_usage").select("*"),supabaseClient.from("expense_profiles").select("*").order("name"),supabaseClient.from("expense_profile_items").select("*")]);const error=results.find(r=>r.error)?.error;if(error){statusEl.textContent=`Sales tracker needs setup: ${error.message}`;return}records=results[0].data||[];expenseItems=results[1].data||[];expenseUsages=results[2].data||[];expenseProfiles=results[3].data||[];profileItems=results[4].data||[];statusEl.textContent="";contentEl.hidden=false;renderExpenseInventory();renderProfiles();render()}
async function loadSales(){const[{data,error},{data:usageData,error:usageError}]=await Promise.all([supabaseClient.from("sales_records").select("*").order("sale_date",{ascending:false}),supabaseClient.from("sales_expense_usage").select("*")]);if(error||usageError)return alert(error?.message||usageError.message);records=data||[];expenseUsages=usageData||[];renderExpenseInventory();render()}
function filtered(){const q=filters.search.value.trim().toLowerCase(),from=filters.from.value?new Date(`${filters.from.value}T00:00:00`):null,to=filters.to.value?new Date(`${filters.to.value}T23:59:59`):null;return records.filter(r=>{const d=new Date(r.sale_date);return(!q||[r.reference,r.customer_name,r.channel].some(v=>String(v||"").toLowerCase().includes(q)))&&(!from||d>=from)&&(!to||d<=to)&&(filters.source.value==="all"||r.source===filters.source.value)&&(filters.status.value==="all"||r.status===filters.status.value)})}
function render(){const rows=filtered(),active=rows.filter(r=>r.status!=="voided"),totalRevenue=active.reduce((s,r)=>s+revenue(r),0),totalExpenses=active.reduce((s,r)=>s+expenses(r),0);summaryEl.innerHTML=`<article class="sales-stat"><span>Recorded sales</span><strong>${active.length}</strong></article><article class="sales-stat"><span>Total revenue</span><strong>${money.format(totalRevenue)}</strong></article><article class="sales-stat"><span>Expense items used</span><strong>${active.reduce((s,r)=>s+usageForSale(r.id).reduce((x,u)=>x+num(u.quantity),0),0)}</strong></article><article class="sales-stat"><span>Total expenses</span><strong>${money.format(totalExpenses)}</strong></article><article class="sales-stat net"><span>Estimated net</span><strong>${money.format(totalRevenue-totalExpenses)}</strong></article>`;if(!rows.length){tableBody.innerHTML='<tr><td colspan="7">No sales match these filters.</td></tr>';cardsEl.innerHTML='<p>No sales match these filters.</p>';return}tableBody.innerHTML=rows.map(r=>`<tr class="${r.status==='voided'?'voided':''}"><td>${new Date(r.sale_date).toLocaleDateString()}</td><td><strong>${esc(r.reference||'—')}</strong><br><small>${esc(r.customer_name||'')}</small></td><td><span class="sales-source">${esc(r.channel||r.source)}</span></td><td>${money.format(revenue(r))}</td><td>${money.format(expenses(r))}</td><td class="net-positive">${money.format(net(r))}</td><td><button class="secondary-button" data-edit-sale="${r.id}">Edit</button> <button class="secondary-button danger" data-delete-sale="${r.id}">Delete</button></td></tr>`).join('');cardsEl.innerHTML=rows.map(r=>`<article class="sales-mobile-card ${r.status==='voided'?'voided':''}"><header><div><strong>${esc(r.reference||'—')}</strong><small>${esc(r.customer_name||'')}</small></div><span class="sales-source">${esc(r.channel||r.source)}</span></header><div class="amount-row"><span>Revenue<br><strong>${money.format(revenue(r))}</strong></span><span>Expenses<br><strong>${money.format(expenses(r))}</strong></span><span>Net<br><strong>${money.format(net(r))}</strong></span></div><p><button class="secondary-button" data-edit-sale="${r.id}">Edit</button> <button class="secondary-button danger" data-delete-sale="${r.id}">Delete</button></p></article>`).join('')}

function renderExpenseInventory(){const value=expenseItems.reduce((s,i)=>s+num(i.quantity_on_hand)*num(i.unit_cost),0);$("#expenseInventoryValue").textContent=`${money.format(value)} inventory`;const select=$("#expensePurchaseForm").elements.itemId,current=select.value;select.innerHTML='<option value="">New expense item</option>'+expenseItems.map(i=>`<option value="${i.id}">${esc(i.name)} (restock)</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;$("#expenseItemsList").innerHTML=expenseItems.length?expenseItems.map(i=>`<article class="expense-rule${i.is_active?'':' is-hidden'}"><div><strong>${esc(i.name)}</strong><small>${i.is_active?`${num(i.default_quantity)} pcs/order · ${money.format(num(i.default_quantity)*num(i.unit_cost))} per order`:'Paused'}</small></div><div class="expense-metric"><small>Used</small><strong>${usedForItem(i.id)} pcs</strong></div><div class="expense-metric ${num(i.quantity_on_hand)<=5?'low-expense-stock':''}"><small>Remaining</small><strong>${num(i.quantity_on_hand)} pcs</strong></div><div class="expense-metric"><small>Cost each</small><strong>${money.format(i.unit_cost)}</strong></div><button class="secondary-button" data-edit-item="${i.id}">Edit</button><button class="secondary-button" data-toggle-item="${i.id}">${i.is_active?'Pause':'Enable'}</button><button class="secondary-button danger" data-delete-item="${i.id}">Delete</button></article>`).join(''):'<p>No packaging or freebie inventory yet.</p>'}
function profileSummary(profileId){const rows=profileItems.filter(x=>String(x.profile_id)===String(profileId));return rows.length?rows.map(x=>{const item=expenseItems.find(i=>String(i.id)===String(x.expense_item_id));return`${item?.name||'Deleted item'} ×${x.quantity} ${x.usage_mode==='per_order'?'once/order':'per product'}`}).join(' · '):'No expense items yet'}
function renderProfiles(){$("#expenseProfilesList").innerHTML=expenseProfiles.length?expenseProfiles.map(p=>`<article class="expense-profile-card"><div><strong>${esc(p.name)}</strong><p>${esc(profileSummary(p.id))}</p></div><div class="expense-profile-actions"><button class="secondary-button" data-edit-profile="${p.id}">Edit</button><button class="secondary-button danger" data-delete-profile="${p.id}">Delete</button></div></article>`).join(''):'<p>No profiles yet. Create “Full Expenses” or “Mailer Only”.</p>'}
function renderSaleUsage(record){const section=$("#saleExpenseUsageSection"),list=$("#saleExpenseUsageList");if(!record){section.hidden=true;list.innerHTML="";return}section.hidden=false;list.innerHTML=expenseItems.map(i=>{const usage=usageForSale(record.id).find(u=>String(u.expense_item_id)===String(i.id)),q=num(usage?.quantity),available=num(i.quantity_on_hand)+q,cost=num(usage?.unit_cost_snapshot||i.unit_cost);return`<label class="sale-expense-row"><div><strong>${esc(i.name)}</strong><small>${money.format(cost)} each · ${available} pcs available including this order</small></div><span>Quantity</span><input type="number" min="0" max="${available}" step="1" value="${q}" data-usage-item="${i.id}" data-unit-cost="${cost}"><strong data-usage-line-total>${money.format(q*cost)}</strong></label>`}).join('')||'<p>Add expense inventory first.</p>';updateUsagePreview();list.querySelectorAll("[data-usage-item]").forEach(input=>input.addEventListener("input",updateUsagePreview))}
function updateUsagePreview(){$("#saleExpenseUsageTotal").textContent=money.format([...document.querySelectorAll("[data-usage-item]")].reduce((s,input)=>{const total=num(input.value)*num(input.dataset.unitCost);input.closest(".sale-expense-row").querySelector("[data-usage-line-total]").textContent=money.format(total);return s+total},0))}
function openForm(record=null){form.reset();form.elements.id.value=record?.id||"";form.elements.source.value=record?.source||"manual";titleEl.textContent=record?"Edit sale":"Add manual sale";form.elements.saleDate.value=localInputDate(record?.sale_date);form.elements.reference.value=record?.reference||"";form.elements.channel.value=record?.channel||"";form.elements.customerName.value=record?.customer_name||"";form.elements.grossAmount.value=num(record?.gross_amount);form.elements.shippingAmount.value=num(record?.shipping_amount);form.elements.costAmount.value=num(record?.cost_amount);form.elements.platformFees.value=num(record?.platform_fees);form.elements.otherExpenses.value=num(record?.other_expenses);form.elements.notes.value=record?.notes||"";formStatus.textContent="";renderSaleUsage(record);dialog.showModal()}
form.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(form),id=String(f.get("id")||""),values={sale_date:new Date(String(f.get("saleDate"))).toISOString(),reference:String(f.get("reference")||"").trim(),channel:String(f.get("channel")||"").trim(),customer_name:String(f.get("customerName")||"").trim()||null,gross_amount:num(f.get("grossAmount")),shipping_amount:num(f.get("shippingAmount")),cost_amount:num(f.get("costAmount")),platform_fees:num(f.get("platformFees")),other_expenses:num(f.get("otherExpenses")),notes:String(f.get("notes")||"").trim()||null,updated_at:new Date().toISOString()};formStatus.textContent="Saving…";let recordId=id;if(id){const{error}=await supabaseClient.from("sales_records").update(values).eq("id",id);if(error){formStatus.textContent=error.message;return}}else{const{data,error}=await supabaseClient.from("sales_records").insert({...values,source:"manual",status:"recorded"}).select("id").single();if(error){formStatus.textContent=error.message;return}recordId=String(data.id)}for(const input of document.querySelectorAll("[data-usage-item]")){const{error}=await supabaseClient.rpc("set_sale_expense_usage",{p_sales_record_id:Number(recordId),p_expense_item_id:Number(input.dataset.usageItem),p_quantity:num(input.value)});if(error){formStatus.textContent=`Sale saved, but expense usage failed: ${error.message}`;await loadAll();return}}dialog.close();await loadAll()});

async function handleSaleAction(e){const edit=e.target.closest("[data-edit-sale]");if(edit)return openForm(records.find(r=>String(r.id)===edit.dataset.editSale));const del=e.target.closest("[data-delete-sale]");if(!del||!confirm("Delete this sales record? Expense pieces used by it will be returned to inventory."))return;const{error}=await supabaseClient.from("sales_records").delete().eq("id",del.dataset.deleteSale);if(error)return alert(error.message);await loadSales()}
tableBody.addEventListener("click",handleSaleAction);cardsEl.addEventListener("click",handleSaleAction);Object.values(filters).forEach(el=>el.addEventListener("input",render));
$("#openManualSale").addEventListener("click",()=>openForm());$("#closeSaleDialog").addEventListener("click",()=>dialog.close());$("#cancelSale").addEventListener("click",()=>dialog.close());
$("#expensePurchaseForm").elements.itemId.addEventListener("change",e=>{const item=expenseItems.find(i=>String(i.id)===e.target.value),name=e.currentTarget.form.elements.name;if(item){name.value=item.name;name.readOnly=true}else{name.value="";name.readOnly=false}});
$("#expensePurchaseForm").addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),status=$("#expensePurchaseStatus"),button=e.currentTarget.querySelector("button[type=submit]");button.disabled=true;status.textContent="Saving purchase…";const{data:itemId,error}=await supabaseClient.rpc("record_expense_purchase",{p_item_id:f.get("itemId")?Number(f.get("itemId")):null,p_name:String(f.get("name")||"").trim(),p_quantity:Number(f.get("quantity")),p_total_cost:num(f.get("totalCost")),p_default_quantity:0});if(error){button.disabled=false;status.textContent=error.message.includes("expense_items_name_key")?"That item already exists. Choose it from the first dropdown to restock it.":error.message;return}const{data:savedItem,error:refreshError}=await supabaseClient.from("expense_items").select("*").eq("id",itemId).single();button.disabled=false;e.currentTarget.reset();e.currentTarget.elements.name.readOnly=false;if(!refreshError&&savedItem){const index=expenseItems.findIndex(i=>String(i.id)===String(savedItem.id));if(index>=0)expenseItems[index]=savedItem;else expenseItems.push(savedItem);expenseItems.sort((a,b)=>a.name.localeCompare(b.name));renderExpenseInventory();renderProfiles()}else await loadAll();status.textContent="Purchase saved and inventory updated."});
function updateItemOrderCost(){itemForm.elements.costPerOrder.value=money.format(num(itemForm.elements.unitCost.value)*num(itemForm.elements.defaultQuantity.value))}
$("#expenseItemsList").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-item]"),toggle=e.target.closest("[data-toggle-item]"),del=e.target.closest("[data-delete-item]");if(edit){const item=expenseItems.find(i=>String(i.id)===edit.dataset.editItem);itemForm.reset();itemForm.elements.id.value=item.id;itemForm.elements.name.value=item.name;itemForm.elements.quantityOnHand.value=num(item.quantity_on_hand);itemForm.elements.unitCost.value=num(item.unit_cost);itemForm.elements.defaultQuantity.value=num(item.default_quantity);updateItemOrderCost();$("#expenseItemFormStatus").textContent="";return itemDialog.showModal()}if(toggle){const item=expenseItems.find(i=>String(i.id)===toggle.dataset.toggleItem);const{error}=await supabaseClient.from("expense_items").update({is_active:!item.is_active,updated_at:new Date().toISOString()}).eq("id",item.id);if(error)return alert(error.message);await loadAll()}if(del&&confirm("Delete this expense item? Items already used in sales or profiles cannot be deleted.")){const{error}=await supabaseClient.from("expense_items").delete().eq("id",del.dataset.deleteItem);if(error)return alert(error.message);await loadAll()}});
itemForm.elements.defaultQuantity.addEventListener("input",updateItemOrderCost);
itemForm.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),status=$("#expenseItemFormStatus");status.textContent="Saving…";const{error}=await supabaseClient.rpc("edit_expense_item",{p_item_id:Number(f.get("id")),p_name:String(f.get("name")||"").trim(),p_quantity_on_hand:Number(f.get("quantityOnHand")),p_unit_cost:num(f.get("unitCost")),p_default_quantity:Number(f.get("defaultQuantity"))});if(error){status.textContent=error.message;return}itemDialog.close();await loadAll()});

function openProfile(profile=null){profileForm.reset();profileForm.elements.id.value=profile?.id||"";profileForm.elements.name.value=profile?.name||"";$("#expenseProfileTitle").textContent=profile?"Edit expense profile":"New expense profile";$("#expenseProfileStatus").textContent="";const assigned=profile?profileItems.filter(x=>String(x.profile_id)===String(profile.id)):[];$("#expenseProfileItems").innerHTML=expenseItems.filter(i=>i.is_active||assigned.some(x=>String(x.expense_item_id)===String(i.id))).map(i=>{const row=assigned.find(x=>String(x.expense_item_id)===String(i.id)),defaultQty=Math.max(1,num(i.default_quantity));return`<div class="profile-item-row"><label><input type="checkbox" data-profile-item="${i.id}" ${row?'checked':''}> <strong>${esc(i.name)}</strong></label><label class="profile-quantity-field">Pieces used<input type="number" min="1" step="1" value="${num(row?.quantity)||defaultQty}" aria-label="Pieces used" data-profile-quantity="${i.id}"></label><select data-profile-mode="${i.id}" aria-label="Usage mode"><option value="per_order" ${row?.usage_mode!=='per_item'?'selected':''}>Once per order</option><option value="per_item" ${row?.usage_mode==='per_item'?'selected':''}>Per product quantity</option></select></div>`}).join('')||'<p>Add an expense inventory item first.</p>';profileDialog.showModal()}
$("#newExpenseProfile").addEventListener("click",()=>openProfile());
$("#expenseProfilesList").addEventListener("click",async e=>{const edit=e.target.closest("[data-edit-profile]"),del=e.target.closest("[data-delete-profile]");if(edit)return openProfile(expenseProfiles.find(p=>String(p.id)===edit.dataset.editProfile));if(del&&confirm("Delete this profile? Products using it will change to no automatic expenses.")){const{error}=await supabaseClient.from("expense_profiles").delete().eq("id",del.dataset.deleteProfile);if(error)return alert(error.message);await loadAll()}});
profileForm.addEventListener("submit",async e=>{e.preventDefault();const f=new FormData(e.currentTarget),items=[...document.querySelectorAll("[data-profile-item]:checked")].map(c=>({expense_item_id:Number(c.dataset.profileItem),quantity:Number(document.querySelector(`[data-profile-quantity="${c.dataset.profileItem}"]`).value),usage_mode:document.querySelector(`[data-profile-mode="${c.dataset.profileItem}"]`).value})),status=$("#expenseProfileStatus");status.textContent="Saving…";const{error}=await supabaseClient.rpc("save_expense_profile",{p_profile_id:f.get("id")?Number(f.get("id")):null,p_name:String(f.get("name")||"").trim(),p_items:items});if(error){status.textContent=error.message;return}profileDialog.close();await loadAll()});
document.querySelectorAll("[data-close-dialog]").forEach(b=>b.addEventListener("click",()=>b.closest("dialog").close()));
$("#exportSales").addEventListener("click",()=>{const rows=filtered(),cell=v=>`"${String(v??"").replaceAll('"','""')}"`,csv=[["Date","Reference","Source","Channel","Customer","Gross","Shipping","Product cost","Fees","Other expenses","Packaging/freebie usage","Total expenses","Net","Status","Notes"],...rows.map(r=>[r.sale_date,r.reference,r.source,r.channel,r.customer_name,r.gross_amount,r.shipping_amount,r.cost_amount,r.platform_fees,r.other_expenses,usageCostForSale(r.id),expenses(r),net(r),r.status,r.notes])].map(row=>row.map(cell).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`wonderpeps-sales-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)});
verifyAccess();
